name: ✨ Feature
description: Suggest an idea for this project
title: "✨ [FEATURE] <title>"
labels: [enhancement]
body:
- type: textarea
  attributes:
    label: Describe what the feature is about?
    description: A concise description of what you expected about the new feature.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the new feature requested!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
